export class CasePayControl
{
  LstUpdUserId : string;
  LstUpdTerminal : string;
  LstUpdTimestamp : Date;
  CodeType : string;
  ProviderType : string;
  ProviderCode : string;
  CaseItemCode : string;
  DteOn : string;
  DteOff : string;
  PtsDays : number;
  CaseStartInd : string;
  CaseItemGroup : string;
  CasePayAmount : number;
  TargetLos : number;
  LongStayDays : number;
  LongStayRate : number;
  ShortStayDays : number;
  PerDiemInd : string;
  ShortStayRate : number;
  IcuDays : number;
  IcuRate1 : number;
  IcuServCode1 : string;
  IcuRate2 : number;
  IcuServCode2 : string;
  IcuRate3 : number;
  IcuServCode3 : string;
  IcuRate4 : number;
  IcuServCode4 : string;
  MaxIcuDays : number;
  IcuPerDiemInd : string;
  PrivAddOnRate : number;
  PrivAddOnInd : string;
  AccessUsedInd : string;
  MedSSRate : number;
  SurgSSRate : number;
  AdvSurgSSRate : number;

}
